#!/bin/sh
#
# discover-host
#
# chkconfig:   2345 99 01
# description: Foreman Discovery script
#

### BEGIN INIT INFO
# Provides: discover-host
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description:
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

NAME=discover-host.rb
DAEMON=/usr/bin/$NAME

start() {
        [ -x $DAEMON ] || exit 5
        echo -n $"Starting $NAME: "

        nohup $DAEMON >/dev/null 2>&1 &
        retval=$?
        echo
        return $retval
}

stop() {
        echo -n $"Stopping $NAME: "

        pkill -f $DAEMON
        retval=$?
        echo
        return $retval
}

restart() {
        stop
        start
}

reload() {
        restart
}

force_reload() {
        restart
}

rh_status() {
        pgrep -f $DAEMON
        if [ $? -eq 0 ]; then
                false
        else
                true
        fi
}

case "$1" in
        start)
                $1
                ;;
        stop)
                $1
                ;;
        restart)
                $1
                ;;
        reload)
                $1
                ;;
        force-reload)
                force_reload
                ;;
        status)
                rh_status
                ;;
        condrestart|try-restart)
                restart
                ;;
        *)
                echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
                exit 2
esac
exit $?

# vim:noet:sw=4:ts=4
