#!/bin/sh
#
# network-dynamic   Configure net interfaces dynamically
#
# chkconfig: 2345 09 91
# description: Configures all network interfaces
#
### BEGIN INIT INFO
# Short-Description: Configures networking dynamically
# Description: Configures networking dynamically
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

configure() {
	for i in /sys/class/net/*; do
		dev=$(basename $i)
		echo -n $"Configuring $dev network interface: "
		script=/etc/sysconfig/network-scripts/ifcfg-$dev
		[ -f $script ] || cat > $script <<EONS
DEVICE=$dev
NM_CONTROLLED=no
ONBOOT=yes
BOOTPROTO=dhcp
EONS
		echo
	done
	return 0
}

case "$1" in
	start)
		configure
		;;
	stop)
		;;
	restart)
		;;
	reload)
		;;
	status)
		;;
	condrestart|try-restart)
		;;
	*)
		echo $"Usage: $0 {start}"
		exit 2
esac
exit $?

# vim:noet:sw=4:ts=4
