#!/bin/sh
#
# network-dynamic   Configure net interfaces dynamically
#
# chkconfig: 2345 09 91
# description: Configures all network interfaces
#
### BEGIN INIT INFO
# Short-Description: Configures networking dynamically
# Description: Configures networking dynamically
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

configure() {
	for i in /sys/class/net/*; do
		dev=$(basename $i)
		[[ "$dev" == "lo" ]] && continue
		mac=$(cat /sys/class/net/$dev/address | tr A-F- a-f:)
		bootif=$(cat /proc/cmdline | grep -io 'BOOTIF=\S*' | tail -n1 | tr A-F- a-f: | cut -d: -f2-7)
		if [[ "$mac" == "$bootif" ]]; then
			peerdns=yes
		else
			peerdns=no
		fi
		echo -n $"Configuring $dev ($mac) network interface: "
		script=/etc/sysconfig/network-scripts/ifcfg-$dev
		cat > $script <<EONS
DEVICE=$dev
NM_CONTROLLED=no
ONBOOT=yes
BOOTPROTO=dhcp
PEERDNS=$peerdns
EONS
		echo
		# prevent from overwriting our configuration
		for SVS in ovirt ovirt-awake ovirt-early ovirt-firstboot ovirt-kdump; do
			chkconfig $SVS off
		done
	done
	return 0
}

case "$1" in
	start)
		configure
		;;
	stop)
		;;
	restart)
		;;
	reload)
		;;
	status)
		;;
	condrestart|try-restart)
		;;
	*)
		echo $"Usage: $0 {start}"
		exit 2
esac
exit $?

# vim:noet:sw=4:ts=4
